{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import numpy as np\n",
    "import os\n",
    "\n",
    "# Create images directory if it doesn't exist\n",
    "if not os.path.exists('images'):\n",
    "    os.makedirs('images')\n",
    "\n",
    "# 1. Load Data\n",
    "# Ensure the CSV is in the same directory or adjust path\n",
    "df = pd.read_csv('fast_food_consumption_health_impact_dataset.csv')\n",
    "\n",
    "# 2. Inspect Data\n",
    "print(\"Dataset Info:\")\n",
    "print(df.info())\n",
    "print(\"\\nFirst 5 Rows:\")\n",
    "print(df.head())\n",
    "\n",
    "# 3. Statistical Analysis\n",
    "# Calculate correlations\n",
    "numeric_df = df.select_dtypes(include=[np.number])\n",
    "corr_matrix = numeric_df.corr()\n",
    "print(\"\\n--- Correlation Analysis ---\")\n",
    "print(f\"Correlation (Fast Food vs BMI): {corr_matrix.loc['Fast_Food_Meals_Per_Week', 'BMI']:.4f}\")\n",
    "print(f\"Correlation (Fast Food vs Health Score): {corr_matrix.loc['Fast_Food_Meals_Per_Week', 'Overall_Health_Score']:.4f}\")\n",
    "\n",
    "# 4. Visualization\n",
    "sns.set(style=\"whitegrid\")\n",
    "\n",
    "# Figure: Composite Dashboard\n",
    "fig = plt.figure(figsize=(20, 15))\n",
    "gs = fig.add_gridspec(3, 3)\n",
    "\n",
    "# Row 1: Distributions\n",
    "ax1 = fig.add_subplot(gs[0, 0])\n",
    "sns.histplot(df['Fast_Food_Meals_Per_Week'], bins=10, kde=True, ax=ax1, color='skyblue')\n",
    "ax1.set_title('Distribution: Fast Food Meals/Week')\n",
    "\n",
    "ax2 = fig.add_subplot(gs[0, 1])\n",
    "sns.histplot(df['BMI'], bins=15, kde=True, ax=ax2, color='salmon')\n",
    "ax2.set_title('Distribution: BMI')\n",
    "\n",
    "ax3 = fig.add_subplot(gs[0, 2])\n",
    "sns.histplot(df['Overall_Health_Score'], bins=10, kde=True, ax=ax3, color='lightgreen')\n",
    "ax3.set_title('Distribution: Health Score')\n",
    "\n",
    "# Row 2: Relationships\n",
    "ax4 = fig.add_subplot(gs[1, 0:2])\n",
    "sns.scatterplot(x='Fast_Food_Meals_Per_Week', y='BMI', hue='Gender', data=df, alpha=0.7, ax=ax4)\n",
    "sns.regplot(x='Fast_Food_Meals_Per_Week', y='BMI', data=df, scatter=False, color='black', ax=ax4)\n",
    "ax4.set_title('BMI vs. Fast Food Consumption')\n",
    "\n",
    "ax5 = fig.add_subplot(gs[1, 2])\n",
    "sns.boxplot(x='Fast_Food_Meals_Per_Week', y='Overall_Health_Score', data=df, palette=\"viridis\", ax=ax5)\n",
    "ax5.set_title('Health Score vs. Fast Food Meals')\n",
    "\n",
    "# Row 3: Categorical & Heatmap\n",
    "ax6 = fig.add_subplot(gs[2, 0])\n",
    "# Binning fast food for cleaner bar chart\n",
    "bins = [0, 2, 5, 10, 20]\n",
    "labels = ['0-2', '3-5', '6-10', '10+']\n",
    "df['Fast_Food_Bin'] = pd.cut(df['Fast_Food_Meals_Per_Week'], bins=bins, labels=labels, include_lowest=True)\n",
    "sns.countplot(x='Fast_Food_Bin', hue='Digestive_Issues', data=df, palette='Set2', ax=ax6)\n",
    "ax6.set_title('Digestive Issues by Consumption Level')\n",
    "\n",
    "ax7 = fig.add_subplot(gs[2, 1:])\n",
    "sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=\".2f\", linewidths=.5, ax=ax7)\n",
    "ax7.set_title('Correlation Matrix')\n",
    "\n",
    "fig.suptitle('Fast Food Consumption & Health Impact Dashboard', fontsize=24)\n",
    "plt.tight_layout()\n",
    "\n",
    "# Save the dashboard\n",
    "output_path = 'images/dashboard.png'\n",
    "plt.savefig(output_path, bbox_inches='tight')\n",
    "print(f\"\\nDashboard saved to {output_path}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1+"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
